sets:
  # icons to import from FontAwesome solid free set
  # NOTE: any solid/regular/brands/etc icons defined in the badger.yaml
  # set will also be included, e.g. angle-left, angle-right
  solid:
    - angle-down
    - angle-up
  # icons to import from FontAwesome regular free set
  regular:
    - circle
    - circle-dot
  # icons to import from FontAwesome brands free set
  brands:
    - github
  # Import all custom icons
  custom: '*'
  # Import all badger icons
  badger: '*'

# define your own icon names mapped to any icons from the solid, regular,
# brands or your custom icon sets
icons:
  ok:           solid:circle-check
  frown:        regular:face-frown
  winner:       custom:star
  badger:       badger:badger-duo